# /app /usr /lib
# FROM --platform=linux/amd64 node:19.2-alpine3.16
# FROM --platform=$BUILDPLATFORM node:19.2-alpine3.16
FROM node:19.2-alpine3.16

# cd app
WORKDIR /app

# Copianmos el package.json en /app
COPY package.json ./

# Instalar dependencias
RUN npm install

# Copiamos todo el código fuente en /app
COPY . .

# Destino /app
RUN npm run test

# Eliminar archivos y directorios no necesarios en PRODUCCIÓN
RUN rm -rf tests && rm -rf node_modules

# Únicamente instala las dependencias de Producción
RUN npm install --prod

# Comando run de la app
CMD [ "node", "app.js" ]
 